apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjavaapi
  template:
    metadata:
      labels:
        app: myjavaapi
    spec:
      containers:
      - name: myjavaapi
        image: cclozano/calculadora-api:'$(Build.BuildNumber)'
        ports:
        - containerPort: 8081
# service type loadbalancer   
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app-svc
spec:
  selector:
    app: myjavaapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer