# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: 
  name: Default
  demands:
    - agent.name -equals cclozano-virtual-machine

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'cclozano/calculadora'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: CopyFiles@2
  inputs:
    Contents: 'azure-aks.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'
    

- task: FileTransform@1
  inputs:
    folderPath: '$(build.artifactstagingdirectory)/**/'
    targetFiles: 'azure-aks.yaml'

- task: CmdLine@2
  inputs:
    script: sed -i 's/calculadora.*/calculadora:$(Build.BuildID)/g' $(build.artifactstagingdirectory)/azure-aks.yaml
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


